category:
  categoryActive: true
  pins:
    Beech_small1:
      name: beech
      iconName: tree
      iconColorRGBA:
        red: 0
        green: 1
        blue: 0
        alpha: 1
      isPermanent: false
      isActive: true
      groupable: true
      groupingDistance: 30
