destructibles:
  categoryConfiguredObjects:
    - AbandonedLogCabin02
    - AbandonedLogCabin03
    - AbandonedLogCabin04
    - AshCrow
    - AshlandRuins
    - Ashlands_floor_large
    - Ashlands_Fortress_Wall_Pillar
    - Ashlands_Fortress_Wall_Pillar_base
    - Ashlands_Fortress_Wall_PillarTop
    - Ashlands_Fortress_Wall_PillarTopStone
    - Ashlands_rock2
    - Ashlands_Ruins_Wall_4x6
    - Ashlands_Ruins_Wall_Windows_Broken_4x6
    - Ashlands_WallBlock
    - AshlandsBranch1
    - AshlandsBranch2
    - AshlandsBranch3
    - AshlandsBush1
    - barrell
    - Beech_small1
    - Beech_small2
    - blackmarble_post01
    - Bush01
    - Bush01_heath
    - Bush02_en
    - caverock_ice_stalagmite
    - caverock_ice_stalagtite
    - Charred_altar_bellfragment
    - CharredRuins1
    - CharredRuins2
    - CharredRuins3
    - CharredRuins4
    - CharredStone_Spawner
    - CharredTowerRuins1
    - CharredTowerRuins1_dvergr
    - CharredTowerRuins2
    - CharredTowerRuins3
    - cliff_ashlands2
    - cliff_ashlands3_Arch_1
    - cliff_ashlands4
    - cliff_ashlands5
    - cliff_ashlands6
    - cliff_ashlands7_HalfArch
    - cliff_mistlands1
    - cliff_mistlands2
    - CreepProp_hanging01
    - Crow
    - Dolmen01
    - Dolmen02
    - Dolmen03
    - dvergrprops_barrel
    - dvergrtown_wood_beam
    - dvergrtown_wood_support
    - FernAshlands
    - FirTree_oldLog
    - FirTree_small
    - FirTree_small_dead
    - FortressRuins
    - goblin_totempole
    - GoblinCamp2
    - Grave1
    - GraveStone_Broken_World
    - Greydwarf_camp1
    - Greydwarf_Root
    - HeathRockPillar
    - highstone
    - ice_rock1
    - ice1
    - InfestedTree01
    - LeviathanLava
    - marker01
    - marker02
    - Mistlands_DvergrBossEntrance1
    - Mistlands_DvergrTownEntrance1
    - Mistlands_DvergrTownEntrance2
    - Mistlands_Excavation3
    - Mistlands_Giant1
    - Mistlands_Giant2
    - Mistlands_GuardTower1_ruined_new
    - Mistlands_GuardTower1_ruined_new2
    - Mistlands_Harbour1
    - Mistlands_RoadPost1
    - Mistlands_RockSpire1
    - Mistlands_Statue1
    - Mistlands_Statue2
    - Mistlands_StatueGroup1
    - Mistlands_Swords3
    - Mistlands_Viaduct1
    - Mistlands_Viaduct2
    - MountainGrave01
    - MountainGraveStone01
    - MountainKit_brazier_blue
    - mudpile_beacon
    - Rock_3
    - Rock_4
    - Rock_4_plains
    - Rock_7
    - rock_mistlands1
    - rock1_mountain
    - rock2_heath
    - rock2_mountain
    - rock3_ice
    - rock3_mountain
    - rock4_coast
    - rock4_forest
    - rock4_heath
    - RockDolmen_1
    - RockDolmen_2
    - RockDolmen_3
    - RockFinger
    - RockFingerBroken
    - RockThumb
    - Ruin1
    - Ruin2
    - Ruin3
    - Seagal
    - ShipSetting01
    - shipwreck_karve_chest
    - ShipWreck01
    - shrub_2
    - shrub_2_heath
    - StoneCircle
    - StoneHenge1
    - StoneHenge2
    - StoneHenge5
    - StoneHenge6
    - StoneHouse3
    - StoneHouse4
    - StoneTower1
    - StoneTower3
    - StoneTowerRuins03
    - StoneTowerRuins04
    - StoneTowerRuins05
    - StoneTowerRuins07
    - StoneTowerRuins08
    - StoneTowerRuins09
    - StoneTowerRuins10
    - stubbe
    - SulfurArch
    - SwampHut1
    - SwampHut2
    - SwampHut3
    - SwampRuin2
    - TreasureChest_blackforest
    - TreasureChest_charredfortress
    - TreasureChest_heath
    - TreasureChest_plains_stone
    - UnstableLavaRock
    - VineAsh
    - volture_strawpile
    - Waymarker01
    - Waymarker02
    - widestone
    - WoodFarm1
    - WoodHouse1
    - WoodHouse10
    - WoodHouse11
    - WoodHouse12
    - WoodHouse13
    - WoodHouse2
    - WoodHouse3
    - WoodHouse5
    - WoodHouse6
    - WoodHouse7
    - WoodHouse8
    - WoodHouse9
    - WoodVillage1
    - YggaShoot_small1
  isActive: false
ores:
  individualConfiguredObjects:
    rock4_copper:
      name: Copper
      isPermanent: true
      isActive: true
    MineRock_Tin:
      name: Tin
      isPermanent: false
      isActive: true
      groupable: true
    MineRock_Obsidian:
      name: Obsidian
      isPermanent: false
      isActive: false
      groupable: true
    silvervein:
      name: Silver
      isPermanent: false
      isActive: false
      groupable: true
    giant_brain:
      name: Brain
      isPermanent: false
      isActive: false
    giant_helmet1:
      name: Helmet
      isPermanent: false
      isActive: false
      groupable: true
    giant_helmet2:
      name: Helmet
      isPermanent: false
      isActive: false
      groupable: true
    giant_ribs:
      name: Ribs
      isPermanent: false
      isActive: false
      groupable: true
    giant_skull:
      name: Skull
      isPermanent: false
      isActive: false
      groupable: true
    giant_sword1:
      name: Sword
      isPermanent: false
      isActive: false
      groupable: true
    giant_sword2:
      name: Sword
      isPermanent: false
      isActive: false
      groupable: true
    GuckSack:
      name: Guck
      isPermanent: false
      isActive: false
      groupable: true
    GuckSack_small:
      name: Guck
      isPermanent: false
      isActive: false
      groupable: true
  isActive: true
  iconName: mine
tarpits:
  categoryConfiguredObjects:
  - TarPit1
  - TarPit2
  - TarPit3
  name: Tar
  isActive: true
  iconName: mine
special:
  categoryConfiguredObjects:
    - StartTemple
    - Hildir_camp
    - Hildir_cave
    - Vendor_BlackForest
  isActive: false
runestones:
  categoryConfiguredObjects:
    - DrakeLorestone
    - Runestone_Ashlands
    - Runestone_Boars
    - Runestone_Greydwarfs
    - Runestone_Meadows
    - Runestone_Mistlands
    - Runestone_Mountains
    - Runestone_Plains
    - Runestone_Swamps
  isActive: true
  iconName: rune
mushrooms:
  categoryConfiguredObjects:
    - Pickable_Mushroom
    - Pickable_Mushroom_yellow
  isActive: false
  iconName: mushroom48
berries:
  categoryConfiguredObjects:
    - RaspberryBush
    - BlueberryBush
    - CloudberryBush
  isActive: false
  iconName: berry48
pickables:
  categoryConfiguredObjects:
    - Pickable_Ashstone
    - Pickable_Barley_Wild
    - Pickable_Branch
    - Pickable_Charredskull
    - Pickable_Dandelion
    - Pickable_DragonEgg
    - Pickable_DvergrLantern
    - Pickable_DvergrStein
    - Pickable_Fiddlehead
    - Pickable_Flax_Wild
    - Pickable_Flint
    - Pickable_ForestCryptRemains01
    - Pickable_ForestCryptRemains02
    - Pickable_ForestCryptRemains03
    - Pickable_MoltenCoreStand
    - Pickable_MountainRemains01_buried
    - Pickable_Mushroom_JotunPuffs
    - Pickable_Mushroom_Magecap
    - Pickable_Pot_Shard
    - Pickable_SeedTurnip
    - Pickable_SmokePuff
    - Pickable_Stone
    - Pickable_SulfurRock
    - Pickable_Swordpiece3
    - Pickable_Tar
    - Pickable_TarBig
    - Pickable_Thistle
    - Pickable_VoltureEgg
  isActive: false
  iconName: hand
seeds:
  individualConfiguredObjects:
    Pickable_SeedCarrot:
      name: Carrot
      isPermanent: false
      isActive: true
      groupable: true
  isActive: true
  iconName: seed
crypt:
  categoryConfiguredObjects:
    - Crypt2
    - Crypt3
    - Crypt4
    - SunkenCrypt4
  name: Crypt
  isActive: true
  isPermanent: true
  iconName: dungeon
morgenholes:
  categoryConfiguredObjects:
    - MorgenHole1
    - MorgenHole2
    - MorgenHole3
  name: Morgen
  isActive: true
  isPermanent: true
  iconName: dungeon
dungeon:
  individualConfiguredObjects:
    CharredFortress:
      name: Fortress
      isPermanent: true
      isActive: true
    MountainCave02:
      name: Cave
      isPermanent: true
      isActive: true
    TrollCave02:
      name: Troll
      isPermanent: true
      isActive: true
  isActive: true
  iconName: dungeon
spawners:
  individualConfiguredObjects:
    FireHole:
      name: Surtlings
      isPermanent: true
      isActive: true
    CharredStone_Spawner:
      name: Skeletons
      isPermanent: true
      isActive: true
    Spawner_GreydwarfNest:
      name: Greydwarves
      isPermanent: true
      isActive: true
    BonePileSpawner:
      name: Skeletons
      isPermanent: true
      isActive: true
    DrakeNest01:
      name: Drakes
      isPermanent: true
      isActive: true
    GraveStone_Broken_CharredTwitcherNest:
      name: Twitcher
      isPermanent: true
      isActive: true
    GraveStone_CharredTwitcherNest:
      name: Twitcher
      isPermanent: true
      isActive: true
    Spawner_CharredCross:
      name: Skeletons
      isPermanent: true
      isActive: true
    Spawner_CharredStone:
      name: Skeletons
      isPermanent: true
      isActive: true
    Spawner_DraugrPile:
      name: Draugr
      isPermanent: true
      isActive: true
    VoltureNest:
      name: Voltures
      isPermanent: true
      isActive: true
  isActive: true
  iconName: spawner
boss_spawners:
  categoryConfiguredObjects:
    - Eikthyrnir
    - GDKing
    - Bonemass
    - Dragonqueen
    - GoblinKing
    - FaderLocation
  isActive: false
treasures:
  categoryConfiguredObjects:
    - Pickable_DolmenTreasure
    - TreasureChest_meadows
    - TreasureChest_meadows_buried
    - TreasureChest_mountains
  isActive: false
